In [15]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [16]:
df = pd.read_csv("C:/Users/preet/Desktop/ML/Datasets/bengaluru_house_prices_bhp.csv")
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

__To find the uniques values of each object columns and its count__

In [18]:
obj_col = df.select_dtypes(include='object').columns
d = {}
for i in obj_col:
    d[i] = {"no of unique values" : df[i].nunique(),  'unique values' : df[i].unique()}

d

{'area_type': {'no of unique values': 4,
  'unique values': array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
         'Carpet  Area'], dtype=object)},
 'availability': {'no of unique values': 81,
  'unique values': array(['19-Dec', 'Ready To Move', '18-May', '18-Feb', '18-Nov', '20-Dec',
         '17-Oct', '21-Dec', '19-Sep', '20-Sep', '18-Mar', '20-Feb',
         '18-Apr', '20-Aug', '18-Oct', '19-Mar', '17-Sep', '18-Dec',
         '17-Aug', '19-Apr', '18-Jun', '22-Dec', '22-Jan', '18-Aug',
         '19-Jan', '17-Jul', '18-Jul', '21-Jun', '20-May', '19-Aug',
         '18-Sep', '17-May', '17-Jun', '21-May', '18-Jan', '20-Mar',
         '17-Dec', '16-Mar', '19-Jun', '22-Jun', '19-Jul', '21-Feb',
         'Immediate Possession', '19-May', '17-Nov', '20-Oct', '20-Jun',
         '19-Feb', '21-Oct', '21-Jan', '17-Mar', '17-Apr', '22-May',
         '19-Oct', '21-Jul', '21-Nov', '21-Mar', '16-Dec', '22-Mar',
         '20-Jan', '21-Sep', '21-Aug', '14-Nov', '19-Nov', '15-Nov',
         '16-Jul', '15-Jun', '17-Feb', '20-Nov', '20-Jul', '16-Sep',
         '15-Oct', '15-Dec', '16-Oct', '22-Nov', '15-Aug', '17-Jan',
         '16-Nov', '20-Apr', '16-Jan', '14-Jul'], dtype=object)},
 'location': {'no of unique values': 1305,
  'unique values': array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
         '12th cross srinivas nagar banshankari 3rd stage',
         'Havanur extension', 'Abshot Layout'], shape=(1306,), dtype=object)},
 'size': {'no of unique values': 31,
  'unique values': array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
         '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
         '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
         '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
         '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
         '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)},
 'society': {'no of unique values': 2688,
  'unique values': array(['Coomee ', 'Theanmp', nan, ..., 'SJovest', 'ThhtsV ', 'RSntsAp'],
        shape=(2689,), dtype=object)},
 'total_sqft': {'no of unique values': 2117,
  'unique values': array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
        shape=(2117,), dtype=object)}}

In [19]:
df["area_type"].unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [20]:
encoder = OneHotEncoder()

In [21]:
# encoded_values = encoder.fit_transform(df["area_type"])
# ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a 
# single row (i.e. single sample) or a single column (i.e. single feature) instead

In [22]:
encoded_values = encoder.fit_transform(df[["area_type"]])
encoded_values

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13320 stored elements and shape (13320, 4)>

In [23]:
encoded_values.shape

(13320, 4)

In [24]:
encoded_values.toarray()   # to see it in array format

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]], shape=(13320, 4))

In [25]:
cols = encoder.get_feature_names_out()   # to get the columns name to understand the above matrix
cols

array(['area_type_Built-up  Area', 'area_type_Carpet  Area',
       'area_type_Plot  Area', 'area_type_Super built-up  Area'],
      dtype=object)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [27]:
obj_df = pd.DataFrame(encoded_values.toarray(), columns=cols)
obj_df

,area_type_Built-up Area,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area
0,0.0,0.0,0.0,1.0
1,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,1.0
...,...,...,...,...
13315,1.0,0.0,0.0,0.0
13316,0.0,0.0,0.0,1.0
13317,1.0,0.0,0.0,0.0
13318,0.0,0.0,0.0,1.0
13319,0.0,0.0,0.0,1.0

In [28]:
encoder = OneHotEncoder(dtype=int, sparse_output=True)
encoded_values = encoder.fit_transform(df[["area_type"]])
encoded_values

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13320 stored elements and shape (13320, 4)>

In [34]:
encoder = OneHotEncoder(dtype=int, sparse_output=False)  # by default sparse_output is True if we give it as false then it will return direct values
encoded_values = encoder.fit_transform(df[["area_type","availability"]])
encoded_values

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], shape=(13320, 85))

In [29]:
encoder = OneHotEncoder(dtype=int, sparse_output=False)  # by default sparse_output is True if we give it as false then it will return direct values
encoded_values = encoder.fit_transform(df[["availability"]])
encoded_values

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], shape=(13320, 81))

In [30]:
# test_values = encoder.transform([['Red']])
# ValueError: Found unknown categories ['Red'] in column 0 during transform

# Why ?
# encoder learns the pattern from from this 4 unique encoded_values
# ['Built-up  Area', 'Carpet  Area', 'Plot  Area', 'Super built-up  Area']

In [31]:
encoder = OneHotEncoder(dtype=int, sparse_output=False, handle_unknown="ignore")
encoded_values = encoder.fit_transform(df[["area_type"]])
encoded_values

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       ...,
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], shape=(13320, 4))

In [32]:
test_value = encoder.transform([['Super built-up  Area']])
test_value

c:\Users\preet\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0, 0, 0, 1]])

In [33]:
test_value = encoder.transform([["Red"]])
test_value

c:\Users\preet\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0, 0, 0, 0]])