In [18]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import GridSearchCV

In [19]:
df = pd.read_csv("C:/Users/preet/Desktop/ML/Datasets/diamonds_d.csv")
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [20]:
df = df.drop(columns=["Unnamed: 0","cut","color","clarity"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   carat   53940 non-null  float64
 1   depth   53940 non-null  float64
 2   table   53940 non-null  float64
 3   price   53940 non-null  int64
 4   x       53940 non-null  float64
 5   y       53940 non-null  float64
 6   z       53940 non-null  float64
dtypes: float64(6), int64(1)
memory usage: 2.9 MB

In [22]:
x = df.drop(columns=["price"])
y = df["price"]
xtrain, xtest, ytrain, ytest = train_test_split(x,y,train_size=0.8,random_state=42)

In [23]:
gridsearchcv = GridSearchCV(
    estimator=KNeighborsRegressor(),
    param_grid={
        "n_neighbors" : [5,201,203,205,207,209,211,213],
        "weights" : ["uniform","distance"],
        "metric" : ["euclidean","manhattan"]
    },
    cv = 5,
)

In [24]:
gridsearchcv.fit(xtrain,ytrain)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [5, 201, 203, 205, 207, 209, 211, 213],
                         'weights': ['uniform', 'distance']})

In [25]:
gridsearchcv.best_params_

{'metric': 'manhattan', 'n_neighbors': 201, 'weights': 'distance'}

In [27]:
val = gridsearchcv.best_estimator_

In [28]:
val.fit(xtrain,ytrain)

KNeighborsRegressor(metric='manhattan', n_neighbors=201, weights='distance')

In [29]:
val.score(xtrain,ytrain)

0.9988898574859044

In [30]:
val.score(xtest,ytest)

0.8836752297709558

In [32]:
df1 = pd.DataFrame(gridsearchcv.cv_results_)
df1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.091017,0.016689,0.139869,0.007306,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.861515,0.861291,0.866315,0.866225,0.865399,0.864149,0.002266,31
1,0.079095,0.002708,0.142841,0.020575,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.859165,0.860531,0.867015,0.865029,0.862652,0.862878,0.002867,32
2,0.089850,0.010015,1.218135,0.060175,euclidean,201,uniform,"{'metric': 'euclidean', 'n_neighbors': 201, 'w...",0.872196,0.868041,0.869492,0.874397,0.873855,0.871596,0.002465,22
3,0.078942,0.003817,1.218432,0.012322,euclidean,201,distance,"{'metric': 'euclidean', 'n_neighbors': 201, 'w...",0.876544,0.873589,0.873427,0.878775,0.877978,0.876063,0.002205,15
4,0.079704,0.002764,1.223538,0.049805,euclidean,203,uniform,"{'metric': 'euclidean', 'n_neighbors': 203, 'w...",0.872109,0.867901,0.869413,0.874305,0.873819,0.871509,0.002487,23
5,0.080131,0.003457,1.245980,0.032311,euclidean,203,distance,"{'metric': 'euclidean', 'n_neighbors': 203, 'w...",0.876485,0.873493,0.873376,0.878714,0.877951,0.876004,0.002217,16
6,0.078697,0.002683,1.207213,0.014541,euclidean,205,uniform,"{'metric': 'euclidean', 'n_neighbors': 205, 'w...",0.872009,0.867823,0.869372,0.874183,0.873692,0.871416,0.002461,24
7,0.079714,0.002180,1.291114,0.083954,euclidean,205,distance,"{'metric': 'euclidean', 'n_neighbors': 205, 'w...",0.876424,0.873444,0.873360,0.878633,0.877874,0.875947,0.002196,17
8,0.082030,0.003207,1.253263,0.045125,euclidean,207,uniform,"{'metric': 'euclidean', 'n_neighbors': 207, 'w...",0.871874,0.867768,0.869358,0.874037,0.873600,0.871327,0.002423,25
9,0.081700,0.005653,1.312422,0.103952,euclidean,207,distance,"{'metric': 'euclidean', 'n_neighbors': 207, 'w...",0.876333,0.873409,0.873351,0.878536,0.877813,0.875888,0.002168,18
10,0.084975,0.003440,1.362915,0.074053,euclidean,209,uniform,"{'metric': 'euclidean', 'n_neighbors': 209, 'w...",0.871831,0.867684,0.869307,0.873936,0.873516,0.871255,0.002416,26
11,0.083847,0.010452,1.316833,0.050271,euclidean,209,distance,"{'metric': 'euclidean', 'n_neighbors': 209, 'w...",0.876311,0.873355,0.873318,0.878459,0.877759,0.875840,0.002159,19
12,0.084431,0.009860,1.291575,0.048886,euclidean,211,uniform,"{'metric': 'euclidean', 'n_neighbors': 211, 'w...",0.871742,0.867581,0.869339,0.873887,0.873487,0.871207,0.002421,27
13,0.079381,0.003088,1.271835,0.025233,euclidean,211,distance,"{'metric': 'euclidean', 'n_neighbors': 211, 'w...",0.876260,0.873291,0.873328,0.878432,0.877737,0.875810,0.002158,20
14,0.078674,0.003191,1.322133,0.061145,euclidean,213,uniform,"{'metric': 'euclidean', 'n_neighbors': 213, 'w...",0.871670,0.867467,0.869237,0.873752,0.873466,0.871118,0.002434,28
15,0.083084,0.005104,1.325531,0.059609,euclidean,213,distance,"{'metric': 'euclidean', 'n_neighbors': 213, 'w...",0.876209,0.873225,0.873266,0.878349,0.877716,0.875753,0.002162,21
16,0.079996,0.002349,0.154733,0.004827,manhattan,5,uniform,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.862849,0.861381,0.868740,0.867801,0.867574,0.865669,0.002965,29
17,0.081459,0.003268,0.156458,0.005413,manhattan,5,distance,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.860049,0.860516,0.869444,0.867378,0.864260,0.864329,0.003696,30
18,0.079998,0.001344,1.317553,0.033865,manhattan,201,uniform,"{'metric': 'manhattan', 'n_neighbors': 201, 'w...",0.879534,0.875447,0.877830,0.882870,0.883139,0.879764,0.002949,8
19,0.079882,0.002608,1.329441,0.033744,manhattan,201,distance,"{'metric': 'manhattan', 'n_neighbors': 201, 'w...",0.881141,0.878292,0.879608,0.884561,0.884126,0.881545,0.002460,1
20,0.079366,0.003814,1.327137,0.036646,manhattan,203,uniform,"{'metric': 'manhattan', 'n_neighbors': 203, 'w...",0.879460,0.875401,0.877806,0.882861,0.883097,0.879725,0.002955,9
21,0.079566,0.003243,1.376242,0.056102,manhattan,203,distance,"{'metric': 'manhattan', 'n_neighbors': 203, 'w...",0.881099,0.878268,0.879586,0.884554,0.884095,0.881520,0.002463,2
22,0.080906,0.003496,1.336928,0.030136,manhattan,205,uniform,"{'metric': 'manhattan', 'n_neighbors': 205, 'w...",0.879456,0.875393,0.877757,0.882842,0.883000,0.879690,0.002937,10
23,0.081030,0.003249,1.370157,0.037212,manhattan,205,distance,"{'metric': 'manhattan', 'n_neighbors': 205, 'w...",0.881100,0.878268,0.879556,0.884542,0.884040,0.881501,0.002453,3
24,0.079178,0.004183,1.348654,0.035889,manhattan,207,uniform,"{'metric': 'manhattan', 'n_neighbors': 207, 'w...",0.879428,0.875319,0.877768,0.882839,0.882917,0.879654,0.002939,11
25,0.077967,0.002969,1.364269,0.032826,manhattan,207,distance,"{'metric': 'manhattan', 'n_neighbors': 207, 'w...",0.881089,0.878225,0.879566,0.884536,0.883999,0.881483,0.002453,4
26,0.077755,0.003706,1.388145,0.065980,manhattan,209,uniform,"{'metric': 'manhattan', 'n_neighbors': 209, 'w...",0.879408,0.875297,0.877739,0.882851,0.882895,0.879638,0.002947,12
27,0.079596,0.002672,1.385580,0.027893,manhattan,209,distance,"{'metric': 'manhattan', 'n_neighbors': 209, 'w...",0.881077,0.878201,0.879553,0.884539,0.883984,0.881471,0.002460,5
28,0.081732,0.002508,1.363052,0.029568,manhattan,211,uniform,"{'metric': 'manhattan', 'n_neighbors': 211, 'w...",0.879390,0.875316,0.877663,0.882849,0.882900,0.879623,0.002953,13
29,0.076906,0.002000,1.390241,0.038787,manhattan,211,distance,"{'metric': 'manhattan', 'n_neighbors': 211, 'w...",0.881071,0.878207,0.879514,0.884537,0.883991,0.881464,0.002466,6
30,0.080387,0.001146,1.391508,0.027053,manhattan,213,uniform,"{'metric': 'manhattan', 'n_neighbors': 213, 'w...",0.879343,0.875268,0.877654,0.882814,0.882854,0.879587,0.002951,14
31,0.080718,0.002080,1.433366,0.033653,manhattan,213,distance,"{'metric': 'manhattan', 'n_neighbors': 213, 'w...",0.881038,0.878180,0.879505,0.884510,0.883969,0.881440,0.002464,7

In [35]:
df1.sort_values(by="rank_test_score")

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
19,0.079882,0.002608,1.329441,0.033744,manhattan,201,distance,"{'metric': 'manhattan', 'n_neighbors': 201, 'w...",0.881141,0.878292,0.879608,0.884561,0.884126,0.881545,0.002460,1
21,0.079566,0.003243,1.376242,0.056102,manhattan,203,distance,"{'metric': 'manhattan', 'n_neighbors': 203, 'w...",0.881099,0.878268,0.879586,0.884554,0.884095,0.881520,0.002463,2
23,0.081030,0.003249,1.370157,0.037212,manhattan,205,distance,"{'metric': 'manhattan', 'n_neighbors': 205, 'w...",0.881100,0.878268,0.879556,0.884542,0.884040,0.881501,0.002453,3
25,0.077967,0.002969,1.364269,0.032826,manhattan,207,distance,"{'metric': 'manhattan', 'n_neighbors': 207, 'w...",0.881089,0.878225,0.879566,0.884536,0.883999,0.881483,0.002453,4
27,0.079596,0.002672,1.385580,0.027893,manhattan,209,distance,"{'metric': 'manhattan', 'n_neighbors': 209, 'w...",0.881077,0.878201,0.879553,0.884539,0.883984,0.881471,0.002460,5
29,0.076906,0.002000,1.390241,0.038787,manhattan,211,distance,"{'metric': 'manhattan', 'n_neighbors': 211, 'w...",0.881071,0.878207,0.879514,0.884537,0.883991,0.881464,0.002466,6
31,0.080718,0.002080,1.433366,0.033653,manhattan,213,distance,"{'metric': 'manhattan', 'n_neighbors': 213, 'w...",0.881038,0.878180,0.879505,0.884510,0.883969,0.881440,0.002464,7
18,0.079998,0.001344,1.317553,0.033865,manhattan,201,uniform,"{'metric': 'manhattan', 'n_neighbors': 201, 'w...",0.879534,0.875447,0.877830,0.882870,0.883139,0.879764,0.002949,8
20,0.079366,0.003814,1.327137,0.036646,manhattan,203,uniform,"{'metric': 'manhattan', 'n_neighbors': 203, 'w...",0.879460,0.875401,0.877806,0.882861,0.883097,0.879725,0.002955,9
22,0.080906,0.003496,1.336928,0.030136,manhattan,205,uniform,"{'metric': 'manhattan', 'n_neighbors': 205, 'w...",0.879456,0.875393,0.877757,0.882842,0.883000,0.879690,0.002937,10
24,0.079178,0.004183,1.348654,0.035889,manhattan,207,uniform,"{'metric': 'manhattan', 'n_neighbors': 207, 'w...",0.879428,0.875319,0.877768,0.882839,0.882917,0.879654,0.002939,11
26,0.077755,0.003706,1.388145,0.065980,manhattan,209,uniform,"{'metric': 'manhattan', 'n_neighbors': 209, 'w...",0.879408,0.875297,0.877739,0.882851,0.882895,0.879638,0.002947,12
28,0.081732,0.002508,1.363052,0.029568,manhattan,211,uniform,"{'metric': 'manhattan', 'n_neighbors': 211, 'w...",0.879390,0.875316,0.877663,0.882849,0.882900,0.879623,0.002953,13
30,0.080387,0.001146,1.391508,0.027053,manhattan,213,uniform,"{'metric': 'manhattan', 'n_neighbors': 213, 'w...",0.879343,0.875268,0.877654,0.882814,0.882854,0.879587,0.002951,14
3,0.078942,0.003817,1.218432,0.012322,euclidean,201,distance,"{'metric': 'euclidean', 'n_neighbors': 201, 'w...",0.876544,0.873589,0.873427,0.878775,0.877978,0.876063,0.002205,15
5,0.080131,0.003457,1.245980,0.032311,euclidean,203,distance,"{'metric': 'euclidean', 'n_neighbors': 203, 'w...",0.876485,0.873493,0.873376,0.878714,0.877951,0.876004,0.002217,16
7,0.079714,0.002180,1.291114,0.083954,euclidean,205,distance,"{'metric': 'euclidean', 'n_neighbors': 205, 'w...",0.876424,0.873444,0.873360,0.878633,0.877874,0.875947,0.002196,17
9,0.081700,0.005653,1.312422,0.103952,euclidean,207,distance,"{'metric': 'euclidean', 'n_neighbors': 207, 'w...",0.876333,0.873409,0.873351,0.878536,0.877813,0.875888,0.002168,18
11,0.083847,0.010452,1.316833,0.050271,euclidean,209,distance,"{'metric': 'euclidean', 'n_neighbors': 209, 'w...",0.876311,0.873355,0.873318,0.878459,0.877759,0.875840,0.002159,19
13,0.079381,0.003088,1.271835,0.025233,euclidean,211,distance,"{'metric': 'euclidean', 'n_neighbors': 211, 'w...",0.876260,0.873291,0.873328,0.878432,0.877737,0.875810,0.002158,20
15,0.083084,0.005104,1.325531,0.059609,euclidean,213,distance,"{'metric': 'euclidean', 'n_neighbors': 213, 'w...",0.876209,0.873225,0.873266,0.878349,0.877716,0.875753,0.002162,21
2,0.089850,0.010015,1.218135,0.060175,euclidean,201,uniform,"{'metric': 'euclidean', 'n_neighbors': 201, 'w...",0.872196,0.868041,0.869492,0.874397,0.873855,0.871596,0.002465,22
4,0.079704,0.002764,1.223538,0.049805,euclidean,203,uniform,"{'metric': 'euclidean', 'n_neighbors': 203, 'w...",0.872109,0.867901,0.869413,0.874305,0.873819,0.871509,0.002487,23
6,0.078697,0.002683,1.207213,0.014541,euclidean,205,uniform,"{'metric': 'euclidean', 'n_neighbors': 205, 'w...",0.872009,0.867823,0.869372,0.874183,0.873692,0.871416,0.002461,24
8,0.082030,0.003207,1.253263,0.045125,euclidean,207,uniform,"{'metric': 'euclidean', 'n_neighbors': 207, 'w...",0.871874,0.867768,0.869358,0.874037,0.873600,0.871327,0.002423,25
10,0.084975,0.003440,1.362915,0.074053,euclidean,209,uniform,"{'metric': 'euclidean', 'n_neighbors': 209, 'w...",0.871831,0.867684,0.869307,0.873936,0.873516,0.871255,0.002416,26
12,0.084431,0.009860,1.291575,0.048886,euclidean,211,uniform,"{'metric': 'euclidean', 'n_neighbors': 211, 'w...",0.871742,0.867581,0.869339,0.873887,0.873487,0.871207,0.002421,27
14,0.078674,0.003191,1.322133,0.061145,euclidean,213,uniform,"{'metric': 'euclidean', 'n_neighbors': 213, 'w...",0.871670,0.867467,0.869237,0.873752,0.873466,0.871118,0.002434,28
16,0.079996,0.002349,0.154733,0.004827,manhattan,5,uniform,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.862849,0.861381,0.868740,0.867801,0.867574,0.865669,0.002965,29
17,0.081459,0.003268,0.156458,0.005413,manhattan,5,distance,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.860049,0.860516,0.869444,0.867378,0.864260,0.864329,0.003696,30
0,0.091017,0.016689,0.139869,0.007306,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.861515,0.861291,0.866315,0.866225,0.865399,0.864149,0.002266,31
1,0.079095,0.002708,0.142841,0.020575,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.859165,0.860531,0.867015,0.865029,0.862652,0.862878,0.002867,32

In [39]:
df = pd.read_csv("C:/Users/preet/Desktop/ML/Datasets/diamonds_d.csv")
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [40]:
df = df.drop(columns=["Unnamed: 0"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [41]:
x = df.drop(columns=["price"])
y = df["price"]
xtrain, xtest, ytrain, ytest = train_test_split(x,y,train_size=0.8,random_state=42)

In [42]:
cat_cols = xtrain.select_dtypes(include="object").columns
num_cols = xtrain.select_dtypes(include="number").columns

In [43]:
for i in cat_cols:
    print(f"{i} -> {x[i].nunique()}")

cut -> 5
color -> 7
clarity -> 8

In [38]:
preprocessing = ColumnTransformer(
    transformers=[
        ("scaler",StandardScaler(),num_cols),
        ("encoder",OneHotEncoder(sparse_output=False, handle_unknown="ignore"),cat_cols)
    ]
)

In [44]:
pipeline = Pipeline(
    steps=[
        ("preprocessing_obj", preprocessing),
        ("model", KNeighborsRegressor())
    ]
)

In [49]:
gscv = GridSearchCV(
    estimator=pipeline,
    param_grid={
        "model__n_neighbors" : [5,201,203,205,207,209,211,213],
        "model__weights" : ["uniform","distance"],
        "model__metric" : ["euclidean","manhattan"]
    },
    cv = 5,
)

In [50]:
gscv.fit(xtrain,ytrain)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing_obj',
                                        ColumnTransformer(transformers=[('scaler',
                                                                         StandardScaler(),
                                                                         Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')),
                                                                        ('encoder',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         Index([], dtype='object'))])),
                                       ('model', KNeighborsRegressor())]),
             param_grid={'model__metric': ['euclidean', 'manhattan'],
                         'model__n_neighbors': [5, 201, 203, 205, 207, 209, 211,
                                                213],
                         'model__weights': ['uniform', 'distance']})

In [51]:
val2 =gscv.best_estimator_

In [52]:
val2.fit(xtrain,ytrain)

Pipeline(steps=[('preprocessing_obj',
                 ColumnTransformer(transformers=[('scaler', StandardScaler(),
                                                  Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  Index([], dtype='object'))])),
                ('model',
                 KNeighborsRegressor(metric='manhattan', n_neighbors=203,
                                     weights='distance'))])

In [53]:
val2.score(xtrain,ytrain)

0.9988898574859044

In [54]:
val2.score(xtest,ytest)

0.8837973411629381